### ISSUE TITLE
missing documentation

### ISSUE THREAD

**Issue by himdel** [hex7c0/arc4#1]
There is no documentation except code, the code is quite readable and fine, but still, one shouldn't have to read code to figure out that encodeString takes cleartext, input_encoding and output_encoding, etc. (And apart from utf-8 and base64 mentioned in examples, I still don't know what the available encodings are.)

**Comment by hex7c0** [comment]
you're right
however all information about encoding are inside node doc http://nodejs.org/api/buffer.html#buffer_new_buffer_str_encoding
