### ISSUE TITLE
RC4A: S2 shouldn't be duplicate of S1 (+ potential solution)

### ISSUE THREAD

**Issue by bryc** [hex7c0/arc4#3]
Your implementation of RC4A disregards the second key `k2` required to produce `S2`, and you instead use `k1`. Thus `S1` and `S2` are duplicates. The correct behavior _should_ be `k2` being PRBG output with `k1` as its seed. Despite that being a loose definition.

A quote from the [original paper on RC4A](https://link.springer.com/content/pdf/10.1007%2F978-3-540-25937-4_16.pdf) regarding this:

> We take one randomly chosen key `k1`.
> Another key `k2` is also generated from a pseudorandom bit generator (e.g. RC4) using `k1` as the seed.
>  Applying the Key Scheduling Algorithm, as described in Fig. 1, we construct two S-boxes `S1`
and `S2` using the keys `k1` and `k2` respectively. 

Unfortunately this description is vague. `k2` is only mentioned twice in the entire paper, which is covered by the above quote. They suggest that a "Pseudo-random bit generator such as RC4" be used, with `k1` being its seed. But RC4 is a stream cipher and requires both a key and message, as does RC4A (and RC4A requires `S2` to progress to the PRBG stage regardless). Are they suggesting one must implement RC4 to implement RC4A? They give no specifics of its implementation. This seemingly left out detail may cause separate implementations of RC4A to not be compatible, due solely to differences in handling `S2`.

The simplest solution to this would be to use the 256-byte output of `S1` as the generative key for `S2`. The only problem with this approach is whether or not RC4's key-scheduling algorithm qualifies as a PRBG as described in the paper. If so, I would highly suggest using it.

**Comment by bryc** [comment]
An [implementation of RC4A in C](https://github.com/cvzakharchenko/Digital-signature/blob/master/other/rc4a.c) is also using the 256 indexes of `S1` to produce `S2`:

```c
rc4new(uint8* key,size_t keylen){
	struct rc4state* state=malloc(sizeof(struct rc4state));
	int i,j;
	state->i= state->j1=state->j2=state->is1=0;
	
	for(i=0;i<256;++i)
		state->s1[i] = state->s2[j] = i; // init s1 and s2 with i from 0 to 255
			
	for(i=0,j=0;i<256;++i){
		j=(j + state->s1[i] + key[i%keylen]) % 256; // produce s1 using key
		swap(state->s1+i, state->s1+j);
	}	
	for(i=0,j=0;i<256;++i){
		j=(j + state->s2[i] + state->s1[i]) % 256; // produce s2 using s1
		swap(state->s2+i, state->s2+j);
	}	
	
	return state;
}
```

**Comment by hex7c0** [comment]
Hi @bryc ,
thank you for this discover!
